apiVersion: v1
kind: Service
metadata:
  name: cricket-score-app-service
spec:
  type: NodePort # Exposes the service on each Node's IP at a static port.
  selector:
    app: cricket-score-app # This must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on inside the cluster
      targetPort: 80 # The port on the container to forward traffic to
      nodePort: 30007 # The port to access the service from outside (on your machine)